# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 481)
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(330, 90, 271, 61))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(parent=Form)
        self.listWidget_2.setGeometry(QtCore.QRect(330, 190, 271, 61))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(parent=Form)
        self.listWidget_3.setGeometry(QtCore.QRect(330, 290, 271, 61))
        self.listWidget_3.setObjectName("listWidget_3")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_3.setGeometry(QtCore.QRect(510, 360, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 380, 581, 61))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_4.setGeometry(QtCore.QRect(510, 260, 87, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_5.setGeometry(QtCore.QRect(510, 160, 87, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(40, 90, 271, 61))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 190, 271, 61))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(40, 290, 271, 61))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(130, 10, 431, 41))
        self.label.setMinimumSize(QtCore.QSize(271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 60, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(450, 70, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(40, 440, 418, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_3.setText(_translate("Form", "値段変更"))
        self.pushButton.setText(_translate("Form", "変更する"))
        self.checkBox_4.setText(_translate("Form", "値段変更"))
        self.checkBox_5.setText(_translate("Form", "値段変更"))
        self.label.setText(_translate("Form", "Webページ駐車場値段変更アプリ"))
        self.label_3.setText(_translate("Form", "変更後プレビュー"))
        self.label_4.setText(_translate("Form", "リスト"))
        self.label_5.setText(_translate("Form", "※このアプリのリストにない価格に変更する場合はエムコミに依頼してプログラムを改造してください。"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
